spring:
  profiles: 
    active: dev

---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: springcloud-config-eureka

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com   #Eureka服务端实例名称
  client:
    fetch-registry: false #自己是注册中心
    register-with-eureka: false #不用向其他注册中心进行注册
    service-url:
      # 单机情况下配自己即可 http://${eureka.instance.hostname}:${server.port}/eureka/  # 注册地址
      # 集群时需要配其他Eureka地址
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/

---
server:
  port: 7001

spring:
  profiles: test
  application:
    name: springcloud-config-eureka

#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com   #Eureka服务端实例名称
  client:
    fetch-registry: false #自己是注册中心
    register-with-eureka: false #不用向其他注册中心进行注册
    service-url:
      # 单机情况下配自己即可 http://${eureka.instance.hostname}:${server.port}/eureka/  # 注册地址
      # 集群时需要配其他Eureka地址
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/

